type exception = NotFoundException | SomethingException

try{
  raise NotFoundException
}catch(NotFoundException){
  print("caught")
}
